name: lodes
channels:
  - conda-forge
dependencies:
  - json-c=0.18
  - python=3.13.9
  - requests=2.32.5
  - networkx=3.6
  - numpy=2.3.5
  - geopandas=1.1.1
  - shapely=2.1.2
  - tqdm=4.67.1
  - osmnx=2.0.7
  - scikit-learn=1.7.2
  - scipy=1.16.3

